#!/usr/bin/env bash
mysql --user=softarch_user --password=12345 --local-infile=1 -e 'USE SA2015; DROP TABLE IF EXISTS Route; CREATE TABLE Route (ID BIGINT NOT NULL AUTO_INCREMENT, Name VARCHAR(255) NOT NULL, PRIMARY KEY(ID)); ALTER TABLE Route AUTO_INCREMENT=5000000; LOAD DATA LOCAL INFILE "./routes.csv" INTO TABLE Route FIELDS TERMINATED BY "|" LINES TERMINATED BY "\r\n" IGNORE 1 LINES;'

mysql --user=softarch_user --password=12345 --local-infile=1 -e 'USE SA2015; DROP TABLE IF EXISTS RouteStop; CREATE TABLE RouteStop (Route_ID BIGINT NOT NULL, Stop_ID BIGINT NOT NULL, OrderKey INT NOT NULL PRIMARY KEY AUTO_INCREMENT); LOAD DATA LOCAL INFILE "./mapping.csv" INTO TABLE RouteStop FIELDS TERMINATED BY "|" LINES TERMINATED BY "\r\n" IGNORE 1 LINES;'

#FOREIGN KEY (Route_ID) REFERENCES Route (ID), FOREIGN KEY (Stop_ID) REFERENCES Stop (ID)
